[package]
name = "coinbase-pro-one-rs"
version = "0.0.1"
authors = ["ae <alson@alsonkemp.com>"]
repository = "https://github.com/alsonkemp/coinbase-pro-one-rs"
description = "Async Coinbase pro client for Rust (fused WS+REST) "
license = "MIT/Apache-2.0"
readme = "README.md"
categories = [ "api-bindings", "cryptography::cryptocurrencies" ]
keywords = [ "async", "exchange", "coinbase", "bitcoin", "websocket" ]

[dependencies]
base64 = ""
chrono = { version = "", features = [ "serde" ] }
failure = ""
futures = ""
hmac = ""
hyper = ""
hyper-tls = ""
log = ""
pretty_env_logger = ""
serde = ""
serde_json = ""
serde_derive = ""
sha2 = ""
time = ""
tokio = ""
tokio-tungstenite = ""
url = ""
uuid = { version = "", features = [ "serde", "v4" ] }

