[package]
name = "coinbase-pro-one-rs"
version = "0.0.1"
authors = ["ae <alson@alsonkemp.com>"]
repository = "https://github.com/alsonkemp/coinbase-pro-one-rs"
description = "Async Coinbase pro client for Rust (fused WS+REST) (See: coinbase-pro-rs)"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = [ "api-bindings", "cryptography::cryptocurrencies" ]
keywords = [ "async", "exchange", "coinbase", "bitcoin", "websocket" ]
homepage = "https://github.com/alsonkemp/coinbase-pro-one-rs"
publish = false

[dependencies]
async-std = "1.6.2"
async-tungstenite = { version = "0.7.0", features = ["async-std-runtime"] }
base64 = ""
chrono = { version = "", features = [ "serde" ] }
failure = ""
futures = ""
futures-channel = ""
hmac = ""
hyper = ""
hyper-tls = ""
log = ""
pretty_env_logger = ""
serde = ""
serde_json = ""
serde_derive = ""
sha2 = ""
tungstenite = ""
time = ""
url = ""
uuid = { version = "", features = [ "serde", "v4" ] }

